package com.example.impulse.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toArgb

enum class ThemePreset(val displayName: String) {
    TERMINAL_GREEN("Terminal Green"),
    AMBER_TERMINAL("Amber Terminal"),
    CYBER_BLUE("Cyber Blue"),
    CRIMSON("Crimson"),
    PURPLE_HAZE("Purple Haze"),
    ICEBERG("Iceberg");
}

data class PaletteTriple(
    val light: ColorSchemeColors,
    val dark: ColorSchemeColors,
    val oled: ColorSchemeColors
)

data class ColorSchemeColors(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val surfaceContainer: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color,
    val outline: Color,
    val outlineVariant: Color,
    val scrim: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
    val inversePrimary: Color,
)

fun ColorSchemeColors.toDarkScheme() = darkColorScheme(
    primary = primary, onPrimary = onPrimary,
    primaryContainer = primaryContainer, onPrimaryContainer = onPrimaryContainer,
    secondary = secondary, onSecondary = onSecondary,
    secondaryContainer = secondaryContainer, onSecondaryContainer = onSecondaryContainer,
    tertiary = tertiary, onTertiary = onTertiary,
    tertiaryContainer = tertiaryContainer, onTertiaryContainer = onTertiaryContainer,
    error = error, onError = onError,
    errorContainer = errorContainer, onErrorContainer = onErrorContainer,
    background = background, onBackground = onBackground,
    surface = surface, onSurface = onSurface,
    surfaceVariant = surfaceVariant, onSurfaceVariant = onSurfaceVariant,
    surfaceContainer = surfaceContainer, surfaceContainerHigh = surfaceContainerHigh,
    surfaceContainerHighest = surfaceContainerHighest,
    outline = outline, outlineVariant = outlineVariant,
    scrim = scrim, inverseSurface = inverseSurface,
    inverseOnSurface = inverseOnSurface, inversePrimary = inversePrimary,
)

fun ColorSchemeColors.toLightScheme() = lightColorScheme(
    primary = primary, onPrimary = onPrimary,
    primaryContainer = primaryContainer, onPrimaryContainer = onPrimaryContainer,
    secondary = secondary, onSecondary = onSecondary,
    secondaryContainer = secondaryContainer, onSecondaryContainer = onSecondaryContainer,
    tertiary = tertiary, onTertiary = onTertiary,
    tertiaryContainer = tertiaryContainer, onTertiaryContainer = onTertiaryContainer,
    error = error, onError = onError,
    errorContainer = errorContainer, onErrorContainer = onErrorContainer,
    background = background, onBackground = onBackground,
    surface = surface, onSurface = onSurface,
    surfaceVariant = surfaceVariant, onSurfaceVariant = onSurfaceVariant,
    surfaceContainer = surfaceContainer, surfaceContainerHigh = surfaceContainerHigh,
    surfaceContainerHighest = surfaceContainerHighest,
    outline = outline, outlineVariant = outlineVariant,
    scrim = scrim, inverseSurface = inverseSurface,
    inverseOnSurface = inverseOnSurface, inversePrimary = inversePrimary,
)

val ThemePalettes: Map<ThemePreset, PaletteTriple> = mapOf(
    // ─────────────────────────────────────────────────
    // 1. TERMINAL GREEN — Matrix classic
    // ─────────────────────────────────────────────────
    ThemePreset.TERMINAL_GREEN to PaletteTriple(
        dark = ColorSchemeColors(
            primary = Color(0xFF00FF41), onPrimary = Color(0xFF003D0E),
            primaryContainer = Color(0xFF006B1E), onPrimaryContainer = Color(0xFFA0FFB0),
            secondary = Color(0xFF00CC33), onSecondary = Color(0xFF00330D),
            secondaryContainer = Color(0xFF005A18), onSecondaryContainer = Color(0xFF88FF99),
            tertiary = Color(0xFF33FF66), onTertiary = Color(0xFF003D0E),
            tertiaryContainer = Color(0xFF006B1E), onTertiaryContainer = Color(0xFFBBFFCC),
            error = Color(0xFFFF4444), onError = Color(0xFF3D0000),
            errorContainer = Color(0xFF6B0000), onErrorContainer = Color(0xFFFFAAAA),
            background = Color(0xFF0A0A0A), onBackground = Color(0xFFD0FFD0),
            surface = Color(0xFF0D0D0D), onSurface = Color(0xFFD0FFD0),
            surfaceVariant = Color(0xFF1A1A1A), onSurfaceVariant = Color(0xFF99CC99),
            surfaceContainer = Color(0xFF111111), surfaceContainerHigh = Color(0xFF1A1A1A),
            surfaceContainerHighest = Color(0xFF242424),
            outline = Color(0xFF336633), outlineVariant = Color(0xFF1A331A),
            scrim = Color.Black, inverseSurface = Color(0xFFE0FFE0),
            inverseOnSurface = Color(0xFF0A1A0A), inversePrimary = Color(0xFF00CC33),
        ),
        light = ColorSchemeColors(
            primary = Color(0xFF008B22), onPrimary = Color.White,
            primaryContainer = Color(0xFFA0FFB0), onPrimaryContainer = Color(0xFF002D0A),
            secondary = Color(0xFF006B18), onSecondary = Color.White,
            secondaryContainer = Color(0xFF88FF99), onSecondaryContainer = Color(0xFF00330D),
            tertiary = Color(0xFF338833), onTertiary = Color.White,
            tertiaryContainer = Color(0xFFBBFFCC), onTertiaryContainer = Color(0xFF003D0E),
            error = Color(0xFFCC2222), onError = Color.White,
            errorContainer = Color(0xFFFFD0D0), onErrorContainer = Color(0xFF3D0000),
            background = Color(0xFFF5FFF5), onBackground = Color(0xFF0A1A0A),
            surface = Color.White, onSurface = Color(0xFF0A1A0A),
            surfaceVariant = Color(0xFFE0F0E0), onSurfaceVariant = Color(0xFF336633),
            surfaceContainer = Color(0xFFEEFFEE), surfaceContainerHigh = Color(0xFFE0F5E0),
            surfaceContainerHighest = Color(0xFFD5ECD5),
            outline = Color(0xFF88AA88), outlineVariant = Color(0xFFCCE0CC),
            scrim = Color.Black, inverseSurface = Color(0xFF1A2A1A),
            inverseOnSurface = Color(0xFFD0FFD0), inversePrimary = Color(0xFF00FF41),
        ),
        oled = ColorSchemeColors(
            primary = Color(0xFF00FF41), onPrimary = Color(0xFF003D0E),
            primaryContainer = Color(0xFF006B1E), onPrimaryContainer = Color(0xFFA0FFB0),
            secondary = Color(0xFF00CC33), onSecondary = Color(0xFF00330D),
            secondaryContainer = Color(0xFF005A18), onSecondaryContainer = Color(0xFF88FF99),
            tertiary = Color(0xFF33FF66), onTertiary = Color(0xFF003D0E),
            tertiaryContainer = Color(0xFF006B1E), onTertiaryContainer = Color(0xFFBBFFCC),
            error = Color(0xFFFF4444), onError = Color(0xFF3D0000),
            errorContainer = Color(0xFF6B0000), onErrorContainer = Color(0xFFFFAAAA),
            background = Color.Black, onBackground = Color(0xFFA0FFB0),
            surface = Color.Black, onSurface = Color(0xFFA0FFB0),
            surfaceVariant = Color(0xFF0D0D0D), onSurfaceVariant = Color(0xFF66AA66),
            surfaceContainer = Color(0xFF050505), surfaceContainerHigh = Color(0xFF0A0A0A),
            surfaceContainerHighest = Color(0xFF121212),
            outline = Color(0xFF1A4A1A), outlineVariant = Color(0xFF0D2A0D),
            scrim = Color.Black, inverseSurface = Color(0xFFD0FFD0),
            inverseOnSurface = Color(0xFF0A1A0A), inversePrimary = Color(0xFF00CC33),
        ),
    ),

    // ─────────────────────────────────────────────────
    // 2. AMBER TERMINAL — vintage VDT
    // ─────────────────────────────────────────────────
    ThemePreset.AMBER_TERMINAL to PaletteTriple(
        dark = ColorSchemeColors(
            primary = Color(0xFFFFB000), onPrimary = Color(0xFF3D2800),
            primaryContainer = Color(0xFF6B4700), onPrimaryContainer = Color(0xFFFFE0A0),
            secondary = Color(0xFFCC8C00), onSecondary = Color(0xFF332200),
            secondaryContainer = Color(0xFF5A3D00), onSecondaryContainer = Color(0xFFFFCC80),
            tertiary = Color(0xFFFFCC33), onTertiary = Color(0xFF3D2D00),
            tertiaryContainer = Color(0xFF6B5000), onTertiaryContainer = Color(0xFFFFE0AA),
            error = Color(0xFFFF4444), onError = Color(0xFF3D0000),
            errorContainer = Color(0xFF6B0000), onErrorContainer = Color(0xFFFFAAAA),
            background = Color(0xFF1A0F00), onBackground = Color(0xFFFFE0A0),
            surface = Color(0xFF1A0F00), onSurface = Color(0xFFFFE0A0),
            surfaceVariant = Color(0xFF2A1A00), onSurfaceVariant = Color(0xFFCCAA66),
            surfaceContainer = Color(0xFF221200), surfaceContainerHigh = Color(0xFF2A1A00),
            surfaceContainerHighest = Color(0xFF332200),
            outline = Color(0xFF664400), outlineVariant = Color(0xFF332200),
            scrim = Color.Black, inverseSurface = Color(0xFFFFF0E0),
            inverseOnSurface = Color(0xFF1A0F00), inversePrimary = Color(0xFFCC8C00),
        ),
        light = ColorSchemeColors(
            primary = Color(0xFF996600), onPrimary = Color.White,
            primaryContainer = Color(0xFFFFE0A0), onPrimaryContainer = Color(0xFF2D1A00),
            secondary = Color(0xFF7A5200), onSecondary = Color.White,
            secondaryContainer = Color(0xFFFFCC80), onSecondaryContainer = Color(0xFF332200),
            tertiary = Color(0xFF886600), onTertiary = Color.White,
            tertiaryContainer = Color(0xFFFFE0AA), onTertiaryContainer = Color(0xFF2D1A00),
            error = Color(0xFFCC2222), onError = Color.White,
            errorContainer = Color(0xFFFFD0D0), onErrorContainer = Color(0xFF3D0000),
            background = Color(0xFFFFF8F0), onBackground = Color(0xFF1A0F00),
            surface = Color.White, onSurface = Color(0xFF1A0F00),
            surfaceVariant = Color(0xFFF0E8D0), onSurfaceVariant = Color(0xFF664400),
            surfaceContainer = Color(0xFFFFF5E8), surfaceContainerHigh = Color(0xFFFFF0D8),
            surfaceContainerHighest = Color(0xFFFFEAC8),
            outline = Color(0xFFBB9966), outlineVariant = Color(0xFFE8DCC8),
            scrim = Color.Black, inverseSurface = Color(0xFF2A1A00),
            inverseOnSurface = Color(0xFFFFE0A0), inversePrimary = Color(0xFFFFB000),
        ),
        oled = ColorSchemeColors(
            primary = Color(0xFFFFB000), onPrimary = Color(0xFF1A0F00),
            primaryContainer = Color(0xFF4D3300), onPrimaryContainer = Color(0xFFFFE0A0),
            secondary = Color(0xFFCC8C00), onSecondary = Color(0xFF1A0F00),
            secondaryContainer = Color(0xFF3D2900), onSecondaryContainer = Color(0xFFFFCC80),
            tertiary = Color(0xFFFFCC33), onTertiary = Color(0xFF1A0F00),
            tertiaryContainer = Color(0xFF4D3B00), onTertiaryContainer = Color(0xFFFFE0AA),
            error = Color(0xFFFF4444), onError = Color(0xFF1A0F00),
            errorContainer = Color(0xFF4D0000), onErrorContainer = Color(0xFFFFAAAA),
            background = Color.Black, onBackground = Color(0xFFFFD080),
            surface = Color.Black, onSurface = Color(0xFFFFD080),
            surfaceVariant = Color(0xFF0D0800), onSurfaceVariant = Color(0xFFAA8844),
            surfaceContainer = Color(0xFF050300), surfaceContainerHigh = Color(0xFF0D0800),
            surfaceContainerHighest = Color(0xFF140E00),
            outline = Color(0xFF442E00), outlineVariant = Color(0xFF221700),
            scrim = Color.Black, inverseSurface = Color(0xFFFFE0A0),
            inverseOnSurface = Color(0xFF1A0F00), inversePrimary = Color(0xFFFFB000),
        ),
    ),

    // ─────────────────────────────────────────────────
    // 3. CYBER BLUE — classic neon cyberpunk
    // ─────────────────────────────────────────────────
    ThemePreset.CYBER_BLUE to PaletteTriple(
        dark = ColorSchemeColors(
            primary = Color(0xFF00D4FF), onPrimary = Color(0xFF003D4D),
            primaryContainer = Color(0xFF006B80), onPrimaryContainer = Color(0xFFA0F0FF),
            secondary = Color(0xFF00AACC), onSecondary = Color(0xFF00333D),
            secondaryContainer = Color(0xFF005A6B), onSecondaryContainer = Color(0xFF88E8FF),
            tertiary = Color(0xFF66E0FF), onTertiary = Color(0xFF003D4D),
            tertiaryContainer = Color(0xFF006B80), onTertiaryContainer = Color(0xFFBBF5FF),
            error = Color(0xFFFF4477), onError = Color(0xFF3D001A),
            errorContainer = Color(0xFF6B0033), onErrorContainer = Color(0xFFFFAACC),
            background = Color(0xFF000D1A), onBackground = Color(0xFFCCE8FF),
            surface = Color(0xFF00101F), onSurface = Color(0xFFCCE8FF),
            surfaceVariant = Color(0xFF001A33), onSurfaceVariant = Color(0xFF77AACC),
            surfaceContainer = Color(0xFF001226), surfaceContainerHigh = Color(0xFF001A33),
            surfaceContainerHighest = Color(0xFF002240),
            outline = Color(0xFF005580), outlineVariant = Color(0xFF002A40),
            scrim = Color.Black, inverseSurface = Color(0xFFE0F0FF),
            inverseOnSurface = Color(0xFF000D1A), inversePrimary = Color(0xFF00AACC),
        ),
        light = ColorSchemeColors(
            primary = Color(0xFF007799), onPrimary = Color.White,
            primaryContainer = Color(0xFFA0F0FF), onPrimaryContainer = Color(0xFF002A3D),
            secondary = Color(0xFF005A73), onSecondary = Color.White,
            secondaryContainer = Color(0xFF88E8FF), onSecondaryContainer = Color(0xFF00333D),
            tertiary = Color(0xFF337799), onTertiary = Color.White,
            tertiaryContainer = Color(0xFFBBF5FF), onTertiaryContainer = Color(0xFF003D4D),
            error = Color(0xFFCC2255), onError = Color.White,
            errorContainer = Color(0xFFFFD0DD), onErrorContainer = Color(0xFF3D001A),
            background = Color(0xFFF0F8FF), onBackground = Color(0xFF00101F),
            surface = Color.White, onSurface = Color(0xFF00101F),
            surfaceVariant = Color(0xFFE0EDF5), onSurfaceVariant = Color(0xFF005580),
            surfaceContainer = Color(0xFFE8F2FA), surfaceContainerHigh = Color(0xFFDCEAF5),
            surfaceContainerHighest = Color(0xFFD0E2F0),
            outline = Color(0xFF77AACC), outlineVariant = Color(0xFFCCE0F0),
            scrim = Color.Black, inverseSurface = Color(0xFF002A40),
            inverseOnSurface = Color(0xFFCCE8FF), inversePrimary = Color(0xFF00D4FF),
        ),
        oled = ColorSchemeColors(
            primary = Color(0xFF00D4FF), onPrimary = Color(0xFF000D1A),
            primaryContainer = Color(0xFF004D66), onPrimaryContainer = Color(0xFFA0F0FF),
            secondary = Color(0xFF00AACC), onSecondary = Color(0xFF000D1A),
            secondaryContainer = Color(0xFF003D4D), onSecondaryContainer = Color(0xFF88E8FF),
            tertiary = Color(0xFF66E0FF), onTertiary = Color(0xFF000D1A),
            tertiaryContainer = Color(0xFF004D66), onTertiaryContainer = Color(0xFFBBF5FF),
            error = Color(0xFFFF4477), onError = Color(0xFF000D1A),
            errorContainer = Color(0xFF4D0026), onErrorContainer = Color(0xFFFFAACC),
            background = Color.Black, onBackground = Color(0xFF99D0FF),
            surface = Color.Black, onSurface = Color(0xFF99D0FF),
            surfaceVariant = Color(0xFF000D14), onSurfaceVariant = Color(0xFF5590B3),
            surfaceContainer = Color(0xFF00080F), surfaceContainerHigh = Color(0xFF00101F),
            surfaceContainerHighest = Color(0xFF001A2E),
            outline = Color(0xFF003A59), outlineVariant = Color(0xFF001A2E),
            scrim = Color.Black, inverseSurface = Color(0xFFCCE8FF),
            inverseOnSurface = Color(0xFF000D1A), inversePrimary = Color(0xFF00D4FF),
        ),
    ),

    // ─────────────────────────────────────────────────
    // 4. CRIMSON — aggressive red
    // ─────────────────────────────────────────────────
    ThemePreset.CRIMSON to PaletteTriple(
        dark = ColorSchemeColors(
            primary = Color(0xFFFF004D), onPrimary = Color(0xFF3D0014),
            primaryContainer = Color(0xFF6B0028), onPrimaryContainer = Color(0xFFFFAACC),
            secondary = Color(0xFFCC0044), onSecondary = Color(0xFF330012),
            secondaryContainer = Color(0xFF5A0022), onSecondaryContainer = Color(0xFFFF88BB),
            tertiary = Color(0xFFFF3377), onTertiary = Color(0xFF3D0014),
            tertiaryContainer = Color(0xFF6B0028), onTertiaryContainer = Color(0xFFFFBBDD),
            error = Color(0xFFFFAA00), onError = Color(0xFF3D2A00),
            errorContainer = Color(0xFF6B4700), onErrorContainer = Color(0xFFFFDDAA),
            background = Color(0xFF1A000A), onBackground = Color(0xFFFFCCDD),
            surface = Color(0xFF1A000A), onSurface = Color(0xFFFFCCDD),
            surfaceVariant = Color(0xFF2A0012), onSurfaceVariant = Color(0xFFCC7799),
            surfaceContainer = Color(0xFF22000F), surfaceContainerHigh = Color(0xFF2A0012),
            surfaceContainerHighest = Color(0xFF33001A),
            outline = Color(0xFF660033), outlineVariant = Color(0xFF33001A),
            scrim = Color.Black, inverseSurface = Color(0xFFFFE0E8),
            inverseOnSurface = Color(0xFF1A000A), inversePrimary = Color(0xFFCC0044),
        ),
        light = ColorSchemeColors(
            primary = Color(0xFF99003D), onPrimary = Color.White,
            primaryContainer = Color(0xFFFFAACC), onPrimaryContainer = Color(0xFF330014),
            secondary = Color(0xFF7A0033), onSecondary = Color.White,
            secondaryContainer = Color(0xFFFF88BB), onSecondaryContainer = Color(0xFF330012),
            tertiary = Color(0xFF993366), onTertiary = Color.White,
            tertiaryContainer = Color(0xFFFFBBDD), onTertiaryContainer = Color(0xFF3D0014),
            error = Color(0xFFCC8800), onError = Color.White,
            errorContainer = Color(0xFFFFE0AA), onErrorContainer = Color(0xFF3D2A00),
            background = Color(0xFFFFF0F4), onBackground = Color(0xFF1A000A),
            surface = Color.White, onSurface = Color(0xFF1A000A),
            surfaceVariant = Color(0xFFF5E0E8), onSurfaceVariant = Color(0xFF660033),
            surfaceContainer = Color(0xFFFFE8EE), surfaceContainerHigh = Color(0xFFFFDDE6),
            surfaceContainerHighest = Color(0xFFFFD0DD),
            outline = Color(0xFFCC7799), outlineVariant = Color(0xFFE8CCD5),
            scrim = Color.Black, inverseSurface = Color(0xFF2A0012),
            inverseOnSurface = Color(0xFFFFCCDD), inversePrimary = Color(0xFFFF004D),
        ),
        oled = ColorSchemeColors(
            primary = Color(0xFFFF004D), onPrimary = Color(0xFF1A000A),
            primaryContainer = Color(0xFF4D001F), onPrimaryContainer = Color(0xFFFFAACC),
            secondary = Color(0xFFCC0044), onSecondary = Color(0xFF1A000A),
            secondaryContainer = Color(0xFF3D001A), onSecondaryContainer = Color(0xFFFF88BB),
            tertiary = Color(0xFFFF3377), onTertiary = Color(0xFF1A000A),
            tertiaryContainer = Color(0xFF4D001F), onTertiaryContainer = Color(0xFFFFBBDD),
            error = Color(0xFFFFAA00), onError = Color(0xFF1A000A),
            errorContainer = Color(0xFF4D3500), onErrorContainer = Color(0xFFFFDDAA),
            background = Color.Black, onBackground = Color(0xFFFFAACC),
            surface = Color.Black, onSurface = Color(0xFFFFAACC),
            surfaceVariant = Color(0xFF0D0006), onSurfaceVariant = Color(0xFFAA5577),
            surfaceContainer = Color(0xFF050003), surfaceContainerHigh = Color(0xFF0D0006),
            surfaceContainerHighest = Color(0xFF14000A),
            outline = Color(0xFF440026), outlineVariant = Color(0xFF220013),
            scrim = Color.Black, inverseSurface = Color(0xFFFFCCDD),
            inverseOnSurface = Color(0xFF1A000A), inversePrimary = Color(0xFFFF004D),
        ),
    ),

    // ─────────────────────────────────────────────────
    // 5. PURPLE HAZE — cryptic purple
    // ─────────────────────────────────────────────────
    ThemePreset.PURPLE_HAZE to PaletteTriple(
        dark = ColorSchemeColors(
            primary = Color(0xFFBB00FF), onPrimary = Color(0xFF2D003D),
            primaryContainer = Color(0xFF4D006B), onPrimaryContainer = Color(0xFFE0AAFF),
            secondary = Color(0xFF9900CC), onSecondary = Color(0xFF260033),
            secondaryContainer = Color(0xFF40005A), onSecondaryContainer = Color(0xFFCC88FF),
            tertiary = Color(0xFFCC44FF), onTertiary = Color(0xFF2D003D),
            tertiaryContainer = Color(0xFF4D006B), onTertiaryContainer = Color(0xFFEEBBFF),
            error = Color(0xFFFF4477), onError = Color(0xFF3D0014),
            errorContainer = Color(0xFF6B0028), onErrorContainer = Color(0xFFFFAACC),
            background = Color(0xFF0A001A), onBackground = Color(0xFFE0CCFF),
            surface = Color(0xFF0D001F), onSurface = Color(0xFFE0CCFF),
            surfaceVariant = Color(0xFF1A0033), onSurfaceVariant = Color(0xFFAA77CC),
            surfaceContainer = Color(0xFF100026), surfaceContainerHigh = Color(0xFF1A0033),
            surfaceContainerHighest = Color(0xFF240040),
            outline = Color(0xFF550080), outlineVariant = Color(0xFF2A0040),
            scrim = Color.Black, inverseSurface = Color(0xFFF0E0FF),
            inverseOnSurface = Color(0xFF0A001A), inversePrimary = Color(0xFF9900CC),
        ),
        light = ColorSchemeColors(
            primary = Color(0xFF7A0099), onPrimary = Color.White,
            primaryContainer = Color(0xFFE0AAFF), onPrimaryContainer = Color(0xFF2A003D),
            secondary = Color(0xFF5A007A), onSecondary = Color.White,
            secondaryContainer = Color(0xFFCC88FF), onSecondaryContainer = Color(0xFF260033),
            tertiary = Color(0xFF773399), onTertiary = Color.White,
            tertiaryContainer = Color(0xFFEEBBFF), onTertiaryContainer = Color(0xFF2D003D),
            error = Color(0xFFCC2255), onError = Color.White,
            errorContainer = Color(0xFFFFD0DD), onErrorContainer = Color(0xFF3D0014),
            background = Color(0xFFF8F0FF), onBackground = Color(0xFF0D001F),
            surface = Color.White, onSurface = Color(0xFF0D001F),
            surfaceVariant = Color(0xFFEEE0F5), onSurfaceVariant = Color(0xFF550080),
            surfaceContainer = Color(0xFFF2E8FA), surfaceContainerHigh = Color(0xFFE8DCF5),
            surfaceContainerHighest = Color(0xFFE0D0F0),
            outline = Color(0xFFAA77CC), outlineVariant = Color(0xFFDDCCE8),
            scrim = Color.Black, inverseSurface = Color(0xFF2A0040),
            inverseOnSurface = Color(0xFFE0CCFF), inversePrimary = Color(0xFFBB00FF),
        ),
        oled = ColorSchemeColors(
            primary = Color(0xFFBB00FF), onPrimary = Color(0xFF0A001A),
            primaryContainer = Color(0xFF3D0059), onPrimaryContainer = Color(0xFFE0AAFF),
            secondary = Color(0xFF9900CC), onSecondary = Color(0xFF0A001A),
            secondaryContainer = Color(0xFF33004D), onSecondaryContainer = Color(0xFFCC88FF),
            tertiary = Color(0xFFCC44FF), onTertiary = Color(0xFF0A001A),
            tertiaryContainer = Color(0xFF3D0059), onTertiaryContainer = Color(0xFFEEBBFF),
            error = Color(0xFFFF4477), onError = Color(0xFF0A001A),
            errorContainer = Color(0xFF4D0024), onErrorContainer = Color(0xFFFFAACC),
            background = Color.Black, onBackground = Color(0xFFCCAAFF),
            surface = Color.Black, onSurface = Color(0xFFCCAAFF),
            surfaceVariant = Color(0xFF080014), onSurfaceVariant = Color(0xFF8855AA),
            surfaceContainer = Color(0xFF05000F), surfaceContainerHigh = Color(0xFF0A001A),
            surfaceContainerHighest = Color(0xFF14002E),
            outline = Color(0xFF3A0059), outlineVariant = Color(0xFF1A002E),
            scrim = Color.Black, inverseSurface = Color(0xFFE0CCFF),
            inverseOnSurface = Color(0xFF0A001A), inversePrimary = Color(0xFFBB00FF),
        ),
    ),

    // ─────────────────────────────────────────────────
    // 6. ICEBERG — cold corporate
    // ─────────────────────────────────────────────────
    ThemePreset.ICEBERG to PaletteTriple(
        dark = ColorSchemeColors(
            primary = Color(0xFF66CCFF), onPrimary = Color(0xFF003D5C),
            primaryContainer = Color(0xFF006699), onPrimaryContainer = Color(0xFFCCF0FF),
            secondary = Color(0xFFA0A0FF), onSecondary = Color(0xFF2D2D5C),
            secondaryContainer = Color(0xFF4D4D99), onSecondaryContainer = Color(0xFFDDDDFF),
            tertiary = Color(0xFF88DDFF), onTertiary = Color(0xFF003D5C),
            tertiaryContainer = Color(0xFF006699), onTertiaryContainer = Color(0xFFDDF5FF),
            error = Color(0xFFFF6688), onError = Color(0xFF3D0022),
            errorContainer = Color(0xFF6B0040), onErrorContainer = Color(0xFFFFCCDD),
            background = Color(0xFF0F172A), onBackground = Color(0xFFDDEEFF),
            surface = Color(0xFF111B30), onSurface = Color(0xFFDDEEFF),
            surfaceVariant = Color(0xFF1A2740), onSurfaceVariant = Color(0xFF99AACC),
            surfaceContainer = Color(0xFF131E33), surfaceContainerHigh = Color(0xFF1A2740),
            surfaceContainerHighest = Color(0xFF22334D),
            outline = Color(0xFF4A6B80), outlineVariant = Color(0xFF263A4D),
            scrim = Color.Black, inverseSurface = Color(0xFFE0EEFF),
            inverseOnSurface = Color(0xFF0F172A), inversePrimary = Color(0xFF3399CC),
        ),
        light = ColorSchemeColors(
            primary = Color(0xFF226699), onPrimary = Color.White,
            primaryContainer = Color(0xFFCCF0FF), onPrimaryContainer = Color(0xFF003352),
            secondary = Color(0xFF555599), onSecondary = Color.White,
            secondaryContainer = Color(0xFFDDDDFF), onSecondaryContainer = Color(0xFF2D2D5C),
            tertiary = Color(0xFF336688), onTertiary = Color.White,
            tertiaryContainer = Color(0xFFDDF5FF), onTertiaryContainer = Color(0xFF003352),
            error = Color(0xFFCC4466), onError = Color.White,
            errorContainer = Color(0xFFFFDDE8), onErrorContainer = Color(0xFF3D0022),
            background = Color(0xFFF0F5FF), onBackground = Color(0xFF111B30),
            surface = Color.White, onSurface = Color(0xFF111B30),
            surfaceVariant = Color(0xFFE0E8F2), onSurfaceVariant = Color(0xFF4A6B80),
            surfaceContainer = Color(0xFFE8EEF8), surfaceContainerHigh = Color(0xFFDDE5F2),
            surfaceContainerHighest = Color(0xFFD0DBEB),
            outline = Color(0xFF99AACC), outlineVariant = Color(0xFFD0DCEB),
            scrim = Color.Black, inverseSurface = Color(0xFF1A2740),
            inverseOnSurface = Color(0xFFDDEEFF), inversePrimary = Color(0xFF66CCFF),
        ),
        oled = ColorSchemeColors(
            primary = Color(0xFF66CCFF), onPrimary = Color(0xFF0F172A),
            primaryContainer = Color(0xFF005580), onPrimaryContainer = Color(0xFFCCF0FF),
            secondary = Color(0xFFA0A0FF), onSecondary = Color(0xFF0F172A),
            secondaryContainer = Color(0xFF3D3D80), onSecondaryContainer = Color(0xFFDDDDFF),
            tertiary = Color(0xFF88DDFF), onTertiary = Color(0xFF0F172A),
            tertiaryContainer = Color(0xFF005580), onTertiaryContainer = Color(0xFFDDF5FF),
            error = Color(0xFFFF6688), onError = Color(0xFF0F172A),
            errorContainer = Color(0xFF550032), onErrorContainer = Color(0xFFFFCCDD),
            background = Color.Black, onBackground = Color(0xFFB0D0FF),
            surface = Color.Black, onSurface = Color(0xFFB0D0FF),
            surfaceVariant = Color(0xFF0D1526), onSurfaceVariant = Color(0xFF7790B3),
            surfaceContainer = Color(0xFF080E1A), surfaceContainerHigh = Color(0xFF0F172A),
            surfaceContainerHighest = Color(0xFF182240),
            outline = Color(0xFF334D66), outlineVariant = Color(0xFF1A2A3D),
            scrim = Color.Black, inverseSurface = Color(0xFFDDEEFF),
            inverseOnSurface = Color(0xFF0F172A), inversePrimary = Color(0xFF66CCFF),
        ),
    ),
)
